# Generated by Django 3.1.7 on 2021-02-27 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_order_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cookie',
            field=models.CharField(default=123456, editable=False, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order_items',
            name='order_number',
            field=models.CharField(default=999999, editable=False, max_length=32),
            preserve_default=False,
        ),
    ]
