# Generated by Django 3.1.7 on 2021-02-28 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_auto_20210227_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_number',
            field=models.CharField(default=999999, editable=False, max_length=32),
            preserve_default=False,
        ),
    ]
