# Generated by Django 3.1.7 on 2021-03-01 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_auto_20210301_1442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer_number',
            new_name='customer_name',
        ),
    ]
