# Generated by Django 3.1.7 on 2021-03-13 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20210313_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('question_number', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='item_number')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=254)),
                ('email', models.EmailField(max_length=254)),
                ('question', models.CharField(max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name='UserQuestion',
        ),
    ]
