# Generated by Django 3.1.7 on 2021-03-17 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0002_auto_20210317_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='item_number',
            field=models.DecimalField(decimal_places=0, max_digits=8),
        ),
    ]
