# Generated by Django 3.1.7 on 2021-02-22 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0002_remove_basket_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
            preserve_default=False,
        ),
    ]
