# Generated by Django 3.1.7 on 2021-02-22 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0004_auto_20210222_0206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='id',
        ),
        migrations.AddField(
            model_name='basket',
            name='item_number',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='item_number'),
            preserve_default=False,
        ),
    ]
