# Generated by Django 3.1.7 on 2021-03-16 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0007_auto_20210316_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='basket',
            name='item_number',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
