# Generated by Django 3.1.7 on 2021-04-05 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_allergies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='allergies',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
