# Generated by Django 3.1.7 on 2021-04-05 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210405_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='course',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
