# Generated by Django 3.1.6 on 2021-02-18 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='options',
            name='options',
        ),
    ]
