# Generated by Django 3.1.7 on 2021-02-21 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_options_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='options',
            name='name',
        ),
        migrations.AddField(
            model_name='options',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category'),
        ),
    ]
