# Generated by Django 3.1.7 on 2021-03-07 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20210306_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='options',
            name='option1',
            field=models.CharField(max_length=24),
        ),
        migrations.AlterField(
            model_name='options',
            name='option2',
            field=models.CharField(max_length=24),
        ),
        migrations.AlterField(
            model_name='options',
            name='option3',
            field=models.CharField(max_length=24),
        ),
    ]
