# Generated by Django 3.1.7 on 2021-03-09 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20210307_1304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sku',
            new_name='id_no',
        ),
        migrations.AddField(
            model_name='category',
            name='id_no',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='options',
            name='id_no',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
