# Generated by Django 3.1.7 on 2021-03-11 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20210309_1720'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='options',
            options={},
        ),
    ]
